# Generated by Django 4.2.18 on 2025-01-31 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiSG', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='phone_number',
            new_name='phone',
        ),
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
